Rating of movie is shown on detailpage in the form of stars
Rasmus3liasson/Next-Kino pull request #20
Opened 2023-05-24 06:48 UTC by burrozd

This is a PR for the ratings of each movie displayed on the detailpage. The code calculates the average rating of each movie which is then rendered under the title of each movie in the form of stars.
<img width="801" alt="Screenshot 2023-05-24 at 08 43 38" src="https://github.com/Rasmus3liasson/Next-Kino/assets/95920902/65936095-dcb6-4ba9-9267-19a6ff372725">

2023-05-24 08:00 UTC, a-jaxell requested changes
Har skrivit en del kommentarer här och där samt förslag på hur du kan ändra så att ratings kommer rätt på 1:a sidan.

Grymt jobbat!

2023-05-24 08:00 UTC, a-jaxell commented on src/components/Rating/index.tsx
> +        /* console.log("API response:", data); */
Här och samt flertalet gånger i dokumentet finns en del loggar, antar att de har varit med för att under utveckling säkerställa att datan kommer igenom som den ska.

De behöver kanske inte vara med ? :)

2023-05-24 08:00 UTC, a-jaxell commented on src/components/Rating/style.module.scss
> +}
Är den här stylingen relevant för komponenten? 
Ser inte nåt ställe där den blir tilldelad på ett element

2023-05-24 08:00 UTC, a-jaxell commented on src/pages/index.tsx
> +      ))}
Det här hamnar utanför och under listan med screenings på huvud sidan när jag testar det.

För att få dem inuti varje screenings behöver du lägga till `Rating` komponenten inuti `Screening` och se till att den får den data den behöver. 
På så sätt kommer det renderas en `Rating` för varje `Screening` som blir renderad.

2023-05-24 09:08 UTC, Rkron91 commented on src/pages/index.tsx
> +      ))}
Home ska väl inte ha någon rating öht? så detta borde bara kunnas ta bort, right?

2023-05-24 09:19 UTC, Rkron91 requested changes
Tror Alvar nailat alla punkter redan!
Dock på startsidan så tror jag inte att det ska finnas några ratings alls, så dem bör bara kunna plockas bort!

kontrollera alltid webläsar consolen innan du anser dig vara klar, så att det inte ligger kvar massa loggar och spottar ut onödig data i consolen :)

2023-05-24 09:29 UTC, burrozd commented
> Har skrivit en del kommentarer här och där samt förslag på hur du kan ändra så att ratings kommer rätt på 1:a sidan.
> 
> Grymt jobbat!

Tack för din review! Jag löser det med en gång. Jag var säker på att vi ej skulle ha med rating på startsidan.

2023-05-24 09:30 UTC, burrozd commented
> Tror Alvar nailat alla punkter redan!
> Dock på startsidan så tror jag inte att det ska finnas några ratings alls, så dem bör bara kunna plockas bort!
> 
> kontrollera alltid webläsar consolen innan du anser dig vara klar, så att det inte ligger kvar massa loggar och spottar ut onödig data i consolen :)

Du har rätt angående loggarna, tar bort de med en gång. Tack!

2023-05-24 10:12 UTC, burrozd commented on src/components/Rating/style.module.scss
> +}
Det har du rätt i, de var kvar från en tidigare version. De är nu borta.

2023-05-24 10:49 UTC, a-jaxell commented
Stjärnorna är fortf längst ned på 1a sidan.
Antingen ta bort dem därifrån eller lägg komponentern för dem inuti ´<Screening />`

2023-05-24 15:19 UTC, a-jaxell approved these changes
Nice, snyggt fixat! :)

2023-05-25 07:43 UTC, Rasmus3liasson approved these changes
Bra jobbat Burak!
Trodde datan erhöll en satt rating men snyggt att du löst uträkningen för att få fram ett medelvärde av recensionerna.
Testat på ett antal filmer och stämmer överens!

2023-05-25 11:21 UTC, Rkron91 approved these changes
Topnotch!

2023-05-25 11:21 UTC, merged

2023-05-25 12:39 UTC, burrozd commented
> Bra jobbat Burak! Trodde datan erhöll en satt rating men snyggt att du löst uträkningen för att få fram ett medelvärde av recensionerna. Testat på ett antal filmer och stämmer överens!

Tack! Det var det jag trodde också från början tills att jag såg vad databasen innehöll.