Search input
Rasmus3liasson/Next-Kino pull request #5
Opened 2023-05-10 15:39 UTC by Rasmus3liasson

Skapat en dropdown från sökfältet i headern där filmerna visas baserat på input från användaren. Innehållet som visas baseras efter filmen title. 
Innehållet visas efter användaren sökning innehåller mer än en bokstav. Skulle inget innehåll matcha så visas text "ingen matchning". 
Plockade även bort sök knappen som befann sig bredvid input fältet 

För tillfället temporär data men kommenterat kod som är en grund för att hämta den data som ska implementeras från databasen

Separerade min styling för headern för att jag tyckte det blev för mycket i huvudfilen.

Kolla gärna om det är något som bör ändras! :)

2023-05-11 08:48 UTC, Rkron91 commented on src/components/Header.tsx
Ser inget som behöver ändras, men kan ge lite feedback på några saker :)
tolka mig inte som en negativ idiot bara! :D idiot går bra, men inte negativ :D

Rad 74 manageInput, konventionen är att använda "handle", 
Tror också att typen på event-parametern hade kunnat vara "KeyboardEvent".
lämnar en länk ang event-types här : [](https://fettblog.eu/typescript-react/events/)

2023-05-11 08:50 UTC, Rkron91 commented on src/styles/sections/header/search.scss
rad 28 och 31 tex, vad är "::-webkit-..." nyfiken bara, hör det till bootstrap?

2023-05-11 08:51 UTC, Rkron91 approved these changes
Snygg sökfunktionalitet!
Solklar Approve!

2023-05-11 10:14 UTC, Rasmus3liasson commented on src/styles/sections/header/search.scss
Det hör till css. Men stylingen appliceras på de webbläsare som stödjer det. Så stylingen ser nog möjligen inte likadan ut i alla webbläsare, hittade inget annat sätt att styla scrollen på

2023-05-11 21:17 UTC, a-jaxell commented on src/styles/sections/header/search.scss
> +      }
Jag hade ändrat till `justify-content: space-between` för att ge bild och text luft emellan för att undvika att det glider som på bilden nedan.

Sen om du lagt till en styling på `img` inuti `a` hade man kunnat krympa bilden lite då den nu enl mig tar för mkt plats  

<img width="274" alt="Untitled 2" src="https://github.com/Rasmus3liasson/Next-Kino/assets/97404672/1b6426ee-e7df-4849-9941-78991220c615">

2023-05-11 21:17 UTC, a-jaxell requested changes
Lite svårt att få överblick då den ligger ibland allt annat i header, hade kanske kunnat gå att
separera i en komponent för att underlätta framtida arbete?

Det är lite fnurr på stylingen med ser jag. 
Bilden glider åt höger beroende på hur lång titel-texten är samt att bilderna är kanske lite väl stora för den här vyn. 

Skriver kommentar i `search.scss`

Annars tycker jag det ser bra ut, ska bli kul att se den fungera med live data. Grymt jobbat! :)

2023-05-11 21:22 UTC, Rasmus3liasson commented
> Lite svårt att få överblick då den ligger ibland allt annat i header, hade kanske kunnat gå att separera i en komponent för att underlätta framtida arbete?
> 
> Det är lite fnurr på stylingen med ser jag. Bilden glider åt höger beroende på hur lång titel-texten är samt att bilderna är kanske lite väl stora för den här vyn.
> 
> Skriver kommentar i `search.scss`
> 
> Annars tycker jag det ser bra ut, ska bli kul att se den fungera med live data. Grymt jobbat! :)

2023-05-11 21:23 UTC, Rasmus3liasson commented
Tar en titt och löser förslagen imorgon !

2023-05-13 06:42 UTC, Rasmus3liasson commented
Gjort några mindre stil ändringar samt lagt sökfunktionen som en component istället. 

Kolla gärna igenom om det ser bra ut.

2023-05-13 11:37 UTC, a-jaxell approved these changes
Ser snyggt ut och är mer överskådligt! Grymt jobbat!

2023-05-13 16:26 UTC, merged